import uuid
import datetime
import json
from typing import Dict, Any, List, Optional

class ArtifactStore:
    """
    Schema-driven Artifact Repository for cross-engine artifact exchange.
    """
    def __init__(self):
        self._artifacts: Dict[str, Dict[str, Any]] = {}

    def create_artifact(
        self,
        artifact_type: str,
        payload: Dict[str, Any],
        title: str,
        engine: str = "compiler",
        source_name: str = "unknown",
        summary: str = ""
    ) -> Dict[str, Any]:
        art_id = str(uuid.uuid4())
        created_at = datetime.datetime.utcnow().isoformat() + "Z"

        artifact = {
            "artifact_id": art_id,
            "artifact_type": artifact_type,
            "schema": artifact_type,
            "created_at": created_at,
            "producer": {
                "engine": engine
            },
            "metadata": {
                "title": title,
                "source_file": source_name,
                "summary": summary or f"{artifact_type} generated by {engine} engine"
            },
            "payload": payload
        }
        self._artifacts[art_id] = artifact
        return artifact

    def get_artifact(self, artifact_id: str) -> Optional[Dict[str, Any]]:
        return self._artifacts.get(artifact_id)

    def list_artifacts(self, artifact_type: Optional[str] = None) -> List[Dict[str, Any]]:
        arts = list(self._artifacts.values())
        if artifact_type:
            arts = [a for a in arts if a["artifact_type"] == artifact_type]
        return sorted(arts, key=lambda x: x["created_at"], reverse=True)

    def convert_compiler_to_ml_dataset(self, compiler_artifact: Dict[str, Any]) -> str:
        """
        Converts Compiler analysis artifact payload into a structured CSV for ML classification/regression!
        Extracts metrics, token counts, decision structures into feature rows.
        """
        payload = compiler_artifact.get("payload", {})
        metrics = payload.get("metrics", {})
        stats = payload.get("stats", {})
        
        # Build synthetic/extracted sample rows representing function/block complexity features
        rows = [
            {
                "loc": metrics.get("total_loc", 10),
                "source_loc": metrics.get("source_loc", 8),
                "cyclomatic_complexity": metrics.get("cyclomatic_complexity", 2),
                "cognitive_complexity": metrics.get("cognitive_complexity", 2),
                "tokens_count": stats.get("tokens_count", 30),
                "keywords_count": stats.get("keywords_count", 5),
                "identifiers_count": stats.get("identifiers_count", 10),
                "diagnostics_count": stats.get("diagnostics_count", 0),
                "risk_level": metrics.get("risk_level", "LOW")
            }
        ]
        
        # Add variation rows derived from Basic Blocks for realistic ML dataset generation
        blocks = payload.get("basic_blocks", [])
        for idx, b in enumerate(blocks):
            inst_cnt = len(b.get("instructions", []))
            rows.append({
                "loc": inst_cnt + 2,
                "source_loc": inst_cnt,
                "cyclomatic_complexity": max(1, inst_cnt // 3 + 1),
                "cognitive_complexity": max(1, inst_cnt // 3),
                "tokens_count": inst_cnt * 4 + 2,
                "keywords_count": max(1, inst_cnt // 2),
                "identifiers_count": max(2, inst_cnt),
                "diagnostics_count": 1 if inst_cnt > 10 else 0,
                "risk_level": "HIGH" if inst_cnt > 10 else ("MODERATE" if inst_cnt > 5 else "LOW")
            })

        import pandas as pd
        df = pd.DataFrame(rows)
        return df.to_csv(index=False)
